# app-deployment.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: formapp-svc
spec:
  selector:
    app: formapp
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: formapp
  labels:
    app: formapp
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: formapp
  template:
    metadata:
      labels:
        app: formapp
    spec:
      containers:
      - name: formapp
        image: "{{ .Values.app.image.name }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "100m"
          requests:
            cpu: "100m"
        ports:
        - containerPort: 5000

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: formapp-hpa
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: formapp
  targetCPUUtilizationPercentage: 20
