apiVersion: apps/v1
kind: Deployment
metadata:
  name: formapp
  labels:
    app: formapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: formapp
  template:
    metadata:
      labels:
        app: formapp
    spec:
      containers:
      - name: formapp
        image: "{{ .Values.app.image.name }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "100m"
          requests:
            cpu: "100m"
        ports:
        - containerPort: 5000

