apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:489653259257:certificate/fc66b5a8-c082-4e10-b2ec-a5b1e6ab0710
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/stickiness.enabled: 'true'
    alb.ingress.kubernetes.io/stickiness.type: 'lb_cookie'
    alb.ingress.kubernetes.io/stickiness.lb_cookie.duration_seconds: '86400'
spec:
  ingressClassName: alb
  rules:
  - host: formapp.sbendarsky.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:489653259257:certificate/fc66b5a8-c082-4e10-b2ec-a5b1e6ab0710
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/stickiness.enabled: 'true'
    alb.ingress.kubernetes.io/stickiness.type: 'lb_cookie'
    alb.ingress.kubernetes.io/stickiness.lb_cookie.duration_seconds: '86400'
spec:
  ingressClassName: alb
  rules:
  - host: formapp.sbendarsky.me
    http:
      paths:
      - path: /argocd
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 8080