apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-mysql
spec:
    storageClassName: ebs-sc  # Use the StorageClass
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 1Gi
    claimRef:
        name: mysql-pv-claim  # Reference to the PVC
