apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |-
    server {
      listen 80;
      index index.html;

      location / {
        add_header From "nginx";
        proxy_pass http://formapp-svc:80;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header user-agent $http_user_agent;
        add_header From "flask";
      }
    }

